### ISSUE TITLE
WHOdhi wrong classiciation term to select - iPath

### ISSUE THREAD

**Issue by VerenaDornauer** [hitontology/database-frontend#20]
@KonradHoeffner 

"Laboratory and diagnostics imgaing" points are not equally to select in database entry.

I would prefer to select "Transmit diagnostic result to healthcare provider" (2.10.1), can't find this entry.

**Comment by KonradHoeffner** [comment]
The WHO DHI catalogues are created from:
https://apps.who.int/iris/bitstream/handle/10665/260480/WHO-RHR-18.06-eng.pdf
https://www.who.int/reproductivehealth/publications/mhealth/WHO_Classifications_Poster.pdf

**Comment by KonradHoeffner** [comment]
There is an error in the source spreadsheet for 2.10.1 and 2.10.2.
This needs to be fixed in the ontology and in the database. References need to be updated as well.

2.10.1 Transmit diagnostic result to healthcare provider 
2.10.2 Transmit and track diagnostic orders

Check also, if there are errors in any of the others. This could have occurred while copy pasting the text from the PDFs.
